server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: library-management
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: library_management
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres?currentSchema=library_management
    username: postgres
    password: 123456
  flyway:
    enabled: true
    schemas: library_management
