version: '3.2'
services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-123456}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 9090:8080

  library-management:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: postgres_db
      BOOK_TEST_DATA_PATH: /initialBooks.json
      USER_TEST_DATA_PATH: /initialUsers.json
      POSTGRES_PASS: ${POSTGRES_PASS:-123456}
    volumes:
      - "${INITIAL_BOOKS_DATA_PATH:-./initialBooks.json}:/initialBooks.json"
      - "${INITIAL_USERS_DATA_PATH:-./initialUsers.json}:/initialUsers.json"
    ports:
      - 8080:8080
