version: '3.2'
services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-123456}
    volumes:
      - "${POSTGRES_DATA_PATH:-/postgres_data}:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 9090:8080

  library-management:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: postgres_db
    ports:
      - 8080:8080
